include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        "results/annotated/all.vcf.gz",
        "results/qc/multiqc.html",
        "results/plots/depths.svg",
        "results/plots/allele-freqs.svg",


##### Modules #####


include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filtering.smk"
include: "rules/stats.smk"
include: "rules/qc.smk"
include: "rules/annotation.smk"
# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
